/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using NetTopologySuite.Geometries;

namespace NLSL.SKS.Package.BusinessLogic.Entities
{
    /// <summary>
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class GeoCoordinate
    {
        public Point Location
        {
            get;
            set;
        }
    }
}