/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;
using System.Collections.Generic;

namespace NLSL.SKS.Package.BusinessLogic.Entities
{
    /// <summary>
    /// </summary>
    [DataContract]
    public class Parcel
    {
        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [Required]
        [DataMember(Name = "weight")]
        [ExcludeFromCodeCoverage]
        public float? Weight
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [Required]
        [DataMember(Name = "recipient")]
        public Recipient Recipient
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [Required]
        [DataMember(Name = "sender")]
        public Recipient Sender
        {
            get;
            set;
        }
        /// <summary>
        /// State of the parcel.
        /// </summary>
        /// <value>State of the parcel.</value>
        [Required]
        [DataMember(Name = "state")]
        public StateEnum? State
        {
            get;
            set;
        }

        /// <summary>
        /// Hops visited in the past.
        /// </summary>
        /// <value>Hops visited in the past.</value>
        [Required]
        [DataMember(Name = "visitedHops")]
        public List<HopArrival> VisitedHops
        {
            get;
            set;
        }

        /// <summary>
        /// Hops coming up in the future - their times are estimations.
        /// </summary>
        /// <value>Hops coming up in the future - their times are estimations.</value>
        [Required]
        [DataMember(Name = "futureHops")]
        public List<HopArrival> FutureHops
        {
            get;
            set;
        }

        [RegularExpression("^[A-Z0-9]{9}$")]
        [DataMember(Name = "trackingId")]
        public string TrackingId
        {
            get;
            set;
        }
    }
}