/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace NLSL.SKS.Package.BusinessLogic.Entities
{
    /// <summary>
    /// </summary>
    [DataContract]
    [ExcludeFromCodeCoverage]
    public class Warehouse : Hop
    {
        /// <summary>
        /// Gets or Sets Level
        /// </summary>
        [Required]
        [DataMember(Name = "level")]
        public int? Level
        {
            get;
            set;
        }

        /// <summary>
        /// Next hops after this warehouse (warehouses or trucks).
        /// </summary>
        /// <value>Next hops after this warehouse (warehouses or trucks).</value>
        [Required]
        [DataMember(Name = "nextHops")]
        public List<WarehouseNextHops> NextHops
        {
            get;
            set;
        }
        [Required]
        [DataMember(Name = "regionGeoJson")]
        public string RegionGeoJson
        {
            get;
            set;
        }

        /// <summary>
        /// The truck&#x27;s number plate.
        /// </summary>
        /// <value>The truck&#x27;s number plate.</value>
        [Required]
        [DataMember(Name = "numberPlate")]
        public string NumberPlate
        {
            get;
            set;
        }

        /// <summary>
        /// Name of the logistics partner.
        /// </summary>
        /// <value>Name of the logistics partner.</value>
        [Required]
        [DataMember(Name = "logisticsPartner")]
        public string LogisticsPartner
        {
            get;
            set;
        }

        /// <summary>
        /// BaseURL of the logistics partner&#x27;s REST service.
        /// </summary>
        /// <value>BaseURL of the logistics partner&#x27;s REST service.</value>
        [Required]
        [DataMember(Name = "logisticsPartnerUrl")]
        public string LogisticsPartnerUrl
        {
            get;
            set;
        }
    }
}